### ISSUE TITLE
Issues with running script in different folder than download folder

### ISSUE THREAD

**Issue by TimKerre** [joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script#10]
Hi,

I managed to get the script going but only in the downloads folder, once I replace the script and try to change to path to the new one it always gives my an error 25. I checked the documentation but I'm unable to resolve this issue myself. Can you tell me what I'm doing wrong? 

I took some screenshots of my current script settings and the error message. Thanks!

<img width="311" alt="Error 25" src="https://user-images.githubusercontent.com/92460324/137175685-14ab9ff8-1c98-4202-8806-e8722fe25e33.png">
<img width="913" alt="Script settings" src="https://user-images.githubusercontent.com/92460324/137175690-c0d05261-5ac0-43ca-a16a-cfcff7683bde.png">

**Comment by joonaspaakko** [comment]
This might not be it, but looking at the screenshot and the error that seems to point to line 1, I have to say I think it'd the "raw" path you have there in the file on line 1.

That's my best guess right now. There might even be other issues after that is removed or commented out with the prefix `//`.
