### ISSUE TITLE
[Request] Ability to group output files into folders named based on the input file used

### ISSUE THREAD

**Issue by RDslva** [joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script#20]
When using this script with a number of input files, I'd love the ability to have them grouped into folders, based on the input file used.

The main use case is generating new mockups for an existing list of products, where you have multiple mockups for a single input. An example might be a photo business, where the input files are the images for sale, and there are 10, 20, 30, etc mockup files that put that image into different backgrounds. Having the output grouped by _input_ would make organizing significantly easier.

**Comment by joonaspaakko** [comment]
I think you need to draw me like a diagram or something, for me to get it.

**Comment by RDslva** [comment]
Let me see if this helps...

Starting Folder Structure:

> 
> _output
> input
>> file 1.jpg
>> file2.jpg
>> file3.jpg

> templates
>> template1.psd
>> template2.psd
>> template3.psd

Currently, if I set 'output.folders' to true, my output folder would look like
>_output
>> template1
>>> template 1 file 1.jpg
>>> template 1 file 2.jpg
>>> etc...

>>template2
>>>template 2 file 1.jpg
>>> etc...


My desired output would be the following
>_output
>> file 1
>>> template 1 file 1.jpg
>>> template 2 file 1.jpg
>>> template 3 file 1.jpg

>> file 2
>>> template 1 file 2.jpg
>>> template 2 file 2.jpg
>>> etc...

![Screenshot 2023-04-02 at 11 08 57 AM](https://user-images.githubusercontent.com/8668575/229361752-e87ccdc0-14ca-425d-ab5f-378d34cb7abe.png)
![Screenshot 2023-04-02 at 11 09 53 AM](https://user-images.githubusercontent.com/8668575/229361754-2ef7d84f-5b8f-4167-89a2-86a669bb43c4.png)
![Screenshot 2023-04-02 at 11 09 38 AM](https://user-images.githubusercontent.com/8668575/229361753-f14a7930-47b3-4860-8905-0aa65ba883cb.png)


Essentially, instead of grouping the output folder based on the 'mockup' or 'template' used, group by the input file used.

**Comment by joonaspaakko** [comment]
So I put on my thinking cap... and realized that it almost already had the capability to do that if you just added a folder structure to the `output.filename`. The only issue was that the `output.filename` wasn't taken into consideration when making new directories, so PS wouldn't have known where to put the files. It needed a very small change and now it does!

So now starting from v.1.7 you can do something like this:
```js
var output = {
  path: './_output files',
  format: 'jpg',
  filename: '@input/@mockup - @input', 
};
```
> _v.1.7 updated in the main repository and the standalone example_

**Comment by RDslva** [comment]
Outstanding! I hadn't thought of using the filename functionality to handle creating folders, as the `folders` property existed. I'll pull the new code and give it ago. Thanks for the update! 👍🏻
